"""Static templates for the small PHP helper files the fixer generates.

Kept as plain string templates (not Jinja) since they are fixed, reviewed
snippets — not per-project data.
"""

DB_PHP = """<?php
// Generated by LegacyLift — shared PDO connection helper.
// Replaces mysql_connect()/mysql_select_db() with a single, reusable,
// exception-throwing PDO connection using utf8mb4.

function get_pdo(): PDO
{
    static $pdo = null;
    if ($pdo !== null) {
        return $pdo;
    }
    $host = getenv('DB_HOST') ?: 'localhost';
    $name = getenv('DB_NAME') ?: 'legacy_school_portal';
    $user = getenv('DB_USER') ?: 'root';
    $pass = getenv('DB_PASSWORD') ?: '';

    $dsn = "mysql:host={$host};dbname={$name};charset=utf8mb4";
    $pdo = new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);
    return $pdo;
}
"""

ESCAPE_PHP = """<?php
// Generated by LegacyLift — output-escaping helper (fixes LL003 / XSS).

function e($value): string
{
    return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
}
"""

AUTH_PHP = """<?php
// Generated by LegacyLift — password verification with a transparent
// rehash-on-login upgrade path (fixes LL004).
//
// Existing users still have an md5() hash in the database. On their next
// successful login we verify against the legacy hash, then immediately
// re-hash the password with password_hash() and persist it — so every
// active account is upgraded within one login cycle with zero downtime
// and no forced password reset.

function legacy_verify_password(string $plain, string $storedHash, PDO $pdo, $userId): bool
{
    // Already migrated: modern hash format.
    if (preg_match('/^\\$2y\\$|^\\$argon2/', $storedHash)) {
        return password_verify($plain, $storedHash);
    }

    // Legacy md5 hash: verify, then upgrade in place.
    if (hash_equals($storedHash, md5($plain))) {
        $newHash = password_hash($plain, PASSWORD_DEFAULT);
        $stmt = $pdo->prepare('UPDATE users SET password = ? WHERE id = ?');
        $stmt->execute([$newHash, $userId]);
        return true;
    }

    return false;
}
"""

CSRF_PHP = """<?php
// Generated by LegacyLift — CSRF token helper (fixes LL005).

function csrf_token(): string
{
    if (session_status() !== PHP_SESSION_ACTIVE) {
        session_start();
    }
    if (empty($_SESSION['csrf_token'])) {
        $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
    }
    return $_SESSION['csrf_token'];
}

function csrf_verify(string $submittedToken): bool
{
    if (session_status() !== PHP_SESSION_ACTIVE) {
        session_start();
    }
    if (empty($_SESSION['csrf_token']) || $submittedToken === '') {
        return false;
    }
    return hash_equals($_SESSION['csrf_token'], $submittedToken);
}
"""

ENV_PHP = """<?php
// Generated by LegacyLift — tiny .env loader (fixes LL011).
// No Composer dependency: reads KEY=VALUE lines from .env into getenv().

function load_env(string $path): void
{
    if (!is_file($path)) {
        return;
    }
    foreach (file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#' || !str_contains($line, '=')) {
            continue;
        }
        [$key, $value] = explode('=', $line, 2);
        $key = trim($key);
        $value = trim($value, " \\t\\n\\r\\0\\x0B\\\"'");
        if (getenv($key) === false) {
            putenv("{$key}={$value}");
        }
    }
}

load_env(__DIR__ . '/../.env');
"""
