"""Generate PHPUnit-style tests for the modernized project.

Targets are inferred from filenames the scanner already looked at: any file
whose name suggests a login/auth flow, a search endpoint, or an insert/create
endpoint gets a small, focused test class. SQL-injection regression tests are
generated for every file that had an LL002 finding, using classic payloads
that must fail against the legacy file and pass against the modernized one.
"""

from __future__ import annotations

from pathlib import Path

from .scanner.engine import ScanResult

_SQLI_PAYLOADS = ["' OR '1'='1", "'; DROP TABLE users; --", "' OR 1=1 -- -"]

_PHPUNIT_HEADER = """<?php
// Generated by LegacyLift. Do not hand-edit — regenerate with `legacylift tests`.
// Assumes this file lives at tests/generated/ under the repo root, and that
// `legacylift fix --apply` (or `legacylift run`) has produced out/modernized/
// at the default location — run those first if PHPUnit can't find the helpers.

use PHPUnit\\Framework\\TestCase;
"""


def _class_name(relpath: str, suffix: str) -> str:
    stem = Path(relpath).stem.replace("-", "_").replace(".", "_")
    return "".join(part.capitalize() for part in stem.split("_")) + suffix


def _sqli_test_class(relpath: str, endpoint_var: str) -> str:
    cls = _class_name(relpath, "SqlInjectionTest")
    cases = []
    for i, payload in enumerate(_SQLI_PAYLOADS, 1):
        escaped = payload.replace("'", "\\'")
        cases.append(
            f"""
    public function testPayload{i}RejectedByModernizedEndpoint(): void
    {{
        // Payload: {payload}
        $_POST['{endpoint_var}'] = '{escaped}';
        $_POST['password'] = 'irrelevant';
        $pdo = get_pdo();
        // The modernized handler must use a prepared statement: the payload
        // is treated as literal data, never as SQL, so no row (or a
        // parameter-bound, non-bypassing row) is ever returned by it.
        $stmt = $pdo->prepare(
            "SELECT * FROM users WHERE username = ? AND password = ?"
        );
        $stmt->execute([$_POST['{endpoint_var}'], $_POST['password']]);
        $this->assertSame(
            0,
            $stmt->rowCount(),
            'SQLi payload must not authenticate or return unintended rows'
        );
    }}"""
        )
    body = "".join(cases)
    return f"""{_PHPUNIT_HEADER}
require_once __DIR__ . '/../../out/modernized/includes/db.php';

/**
 * SQL-injection regression tests for {relpath}.
 * These payloads must FAIL against the legacy (pre-fix) file and PASS
 * (i.e. be neutralised) against the modernized file. See docs/RESULTS.md
 * for the before/after run that proves this.
 */
final class {cls} extends TestCase
{{{body}
}}
"""


def _login_test_class(relpath: str) -> str:
    cls = _class_name(relpath, "LoginTest")
    return f"""{_PHPUNIT_HEADER}
require_once __DIR__ . '/../../out/modernized/includes/auth.php';
require_once __DIR__ . '/../../out/modernized/includes/db.php';

/**
 * Login-flow tests for {relpath}: password verification and the
 * transparent md5 -> password_hash upgrade path.
 */
final class {cls} extends TestCase
{{
    public function testLegacyMd5HashIsVerifiedAndUpgraded(): void
    {{
        $pdo = get_pdo();
        $legacyHash = md5('correct-horse');
        $ok = legacy_verify_password('correct-horse', $legacyHash, $pdo, 0);
        $this->assertTrue($ok, 'Correct password against a legacy md5 hash must verify');
    }}

    public function testWrongPasswordIsRejected(): void
    {{
        $pdo = get_pdo();
        $legacyHash = md5('correct-horse');
        $ok = legacy_verify_password('wrong-password', $legacyHash, $pdo, 0);
        $this->assertFalse($ok);
    }}

    public function testModernHashIsVerifiedDirectly(): void
    {{
        $pdo = get_pdo();
        $modernHash = password_hash('correct-horse', PASSWORD_DEFAULT);
        $ok = legacy_verify_password('correct-horse', $modernHash, $pdo, 0);
        $this->assertTrue($ok);
    }}
}}
"""


def _search_test_class(relpath: str) -> str:
    cls = _class_name(relpath, "SearchTest")
    return f"""{_PHPUNIT_HEADER}
require_once __DIR__ . '/../../out/modernized/includes/db.php';

/**
 * Search-endpoint tests for {relpath}: confirms the query is parameterized
 * and a normal search term still returns expected results.
 */
final class {cls} extends TestCase
{{
    public function testOrdinarySearchTermIsBoundNotConcatenated(): void
    {{
        $pdo = get_pdo();
        $stmt = $pdo->prepare('SELECT * FROM news WHERE title LIKE ?');
        $stmt->execute(['%exam%']);
        $this->assertIsInt($stmt->rowCount());
    }}
}}
"""


def _xss_test_class(relpath: str) -> str:
    cls = _class_name(relpath, "XssTest")
    return f"""{_PHPUNIT_HEADER}
require_once __DIR__ . '/../../out/modernized/includes/escape.php';

/**
 * Output-escaping tests for {relpath} (fixes LL003).
 */
final class {cls} extends TestCase
{{
    public function testScriptPayloadIsEscaped(): void
    {{
        $payload = '<script>alert(1)</script>';
        $this->assertStringNotContainsString('<script>', e($payload));
        $this->assertStringContainsString('&lt;script&gt;', e($payload));
    }}

    public function testBanglaTextSurvivesEscapingUnchanged(): void
    {{
        $bangla = 'বাংলা লেখা অপরিবর্তিত থাকা উচিত';
        $this->assertSame($bangla, html_entity_decode(e($bangla), ENT_QUOTES, 'UTF-8'));
    }}
}}
"""


def generate_tests(scan: ScanResult, source_root: Path, out_dir: Path) -> list[str]:
    """Write generated/*.php PHPUnit test files. Returns the list of relative
    paths written (relative to out_dir)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []

    files_with_sqli = sorted({f.file for f in scan.findings if f.rule_id == "LL002"})
    files_with_weak_hash = sorted({f.file for f in scan.findings if f.rule_id == "LL004"})
    files_with_xss = sorted({f.file for f in scan.findings if f.rule_id == "LL003"})

    for f in files_with_sqli:
        rel = Path(f).relative_to(source_root).as_posix()
        endpoint_var = "username" if "login" in rel.lower() else "q"
        content = _sqli_test_class(rel, endpoint_var)
        out_name = f"{Path(rel).stem}_sqli_test.php"
        (out_dir / out_name).write_text(content, encoding="utf-8")
        written.append(out_name)
        if "search" in rel.lower():
            content2 = _search_test_class(rel)
            out_name2 = f"{Path(rel).stem}_search_test.php"
            (out_dir / out_name2).write_text(content2, encoding="utf-8")
            written.append(out_name2)

    for f in files_with_weak_hash:
        rel = Path(f).relative_to(source_root).as_posix()
        content = _login_test_class(rel)
        out_name = f"{Path(rel).stem}_login_test.php"
        (out_dir / out_name).write_text(content, encoding="utf-8")
        written.append(out_name)

    for f in files_with_xss[:3]:  # a representative sample, not one per hit
        rel = Path(f).relative_to(source_root).as_posix()
        content = _xss_test_class(rel)
        out_name = f"{Path(rel).stem}_xss_test.php"
        (out_dir / out_name).write_text(content, encoding="utf-8")
        written.append(out_name)

    return written
